name: "Regular CI Build"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Sophon Build
        run: |
          ./build-sophon.sh

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: |
          ./configure.sh
          pnpm run lint
          YAAGL_CHANNEL_CLIENT=hk4ecn node ./build-app.js
          YAAGL_CHANNEL_CLIENT=hk4eos node ./build-app.js
          YAAGL_CHANNEL_CLIENT=bh3glb node ./build-app.js
          YAAGL_CHANNEL_CLIENT=hoyoplaycn node ./build-app.js
